from django.conf.urls import include
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django_email_verification import urls as main_urls

urlpatterns = [
    path('',views.index, name='index'),
    path('index/', views.index, name='index'),
    path('sendEmail/', views.sendEmail, name='sendEmail'),
    path('email/', include(main_urls)),
    path('departments/', views.departments, name='departments'),
    path('about/',views.about, name='about'),
    path('baptism/',views.baptism, name='baptism'),
    path('church_reg/',views.church_reg, name='church_reg'),
    path('clusters/',views.clusters, name='clusters'),
    path('communion/',views.communion, name='communion'),
    path('contact/',views.contact, name='contact'),
    path('dept_form/',views.dept_form, name='dept_form'),
    path('forms/',views.forms, name='forms'),
    path('kama/',views.kama, name='kama'),
    path('mu/',views.mu, name='mu'),
    path('register_manual/',views.register_manual, name='register_manual'),
    path('registration/',views.registration, name='registration'),
    path('staff_members/',views.staff_members, name='staff_members'),
    path('sundayschool/',views.sundayschool, name='sundayschool'),
    path('wedding/',views.wedding, name='wedding'),
    path('youth/',views.youth, name='youth'),
    path('clusters/',views.clusters, name='clusters'),
    path('teens/',views.teens, name='teens'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('meeting_calender/', views.meeting_calender, name='meeting_calender'),
    path('account_list/', views.account_list, name='account_list'),
    path('view_group/', views.view_group, name='view_group'),
    path('view_info/', views.view_info, name='view_info'),
    path('dependent_view/<account_id>/', views.dependent_view, name='dependent_view'),
    path('superdependent_update/<account_id>/', views.superdependent_update, name='superdependent_update'),
    path('account_edit/<account_id>/', views.account_edit, name='account_edit'),
    path('dependent_register/<account_id>/', views.dependent_register, name='dependent_register'),
    path('dependent_update/<account_id>/', views.dependent_update, name='dependent_update'),
    path('superuser_home/', views.superuser_home, name='superuser_home'),
    path('admin_home/', views.admin_home, name='admin_home'),
    path('superuser_edit/<account_id>/', views.superuser_edit, name='superuser_edit'),
    path('make_user/<account_id>/', views.make_user, name='make_user'),
    path('make_superuser/<account_id>/', views.make_superuser, name='make_superuser'),
    path('make_admin/<account_id>/', views.make_admin, name='make_admin'),
    path('delete_individual/<account_id>/', views.delete_individual, name='delete_individual'),
    path('update_account/', views.update_account, name='update_account'),
    path('update_group/<user_id>/', views.update_group, name='update_group'),
    path('dependent_group/<account_id>/', views.dependent_group, name='dependent_group'),
    path('filter/', views.filter, name='filter'),
    path('filter_all/', views.filter_all, name='filter_all'),
    path('userhome/', views.userhome, name='userhome'),
    path('admin_home/', views.admin_home, name='admin_home'),
    path('superuser_home/', views.superuser_home, name='superuser_home'),
    path('church_accounts/', views.church_accounts, name='church_accounts'),
    path('all_sms/', views.all_sms, name='all_sms'),
    path('send_sms/', views.send_sms, name='send_sms'),
    path('department_sms/', views.department_sms, name='department_sms'),
    path('send_all/', views.send_all, name='send_all'),
    path('create_email/', views.create_email, name='create_email'),
    path('send_email/', views.send_email, name='send_email'),
    path('emails/', views.emails, name='emails'),
    path('email_department/', views.email_department, name='email_department'),
    path('offering/', views.offering, name='offering'),
    path('dependent_list/', views.dependent_list, name='dependent_list'),
    path('download_file/', views.download_file, name='download_file'),
    path('send_smss/', views.send_smss, name='send_smss'),
    path('dependent_filter/', views.dependent_filter, name='dependent_filter'),
    path('dependent_all/', views.dependent_all, name='dependent_all'),
    path('dependent_delete/<account_id>/', views.dependent_delete, name='dependent_delete'),
    path('group_members/', views.group_members, name='group_members'),
    path('profile/', views.profile, name='profile'),
    path('change_group/', views.change_group, name='change_group'),
    path('admin_talent/', views.admin_talent, name='admin_talent'),
    path('admin_department/', views.admin_department, name='admin_department'),
    path('admin_cluster/', views.admin_cluster, name='admin_cluster'),
    path('department_view/', views.department_view, name='department_view'),
    path('department_adminemail/', views.department_adminemail, name='department_adminemail'),
    path('department_adminsms/', views.department_adminsms, name='department_adminsms'),
    path('add_department/', views.add_department, name='add_department'),   
    path('dept_add/', views.dept_add, name='dept_add'),   
    path('delete_dept/<group_id>/', views.delete_dept, name='delete_dept'),   
    path('edit_dept/<group_id>/', views.edit_dept, name='edit_dept'),   
    path('group_list/', views.group_list, name='group_list'),
    path('add_staffmember/', views.add_staffmember, name='add_staffmember'),
    path('success/', views.success, name='success'),
    path('excel_uploadattendance/', views.excel_uploadattendance, name='excel_uploadattendance'),
    path('message_noattendance/', views.message_noattendance, name='message_noattendance'),
    path('email_noattendance/', views.email_noattendance, name='email_noattendance'),
    path('add_activity/', views.add_activity, name='add_activity'),
    path('event_application/', views.event_application, name='event_application'),
    path('user_application/', views.user_application, name='user_application'),
    path('superuser_application/', views.superuser_application, name='superuser_application'),
    path('view_event/', views.view_event, name='view_event'),
    path('application_satus/', views.application_satus, name='application_satus'),
    path('application_accept/<app_id>', views.application_accept, name='application_accept'),
    path('application_reject/<app_id>', views.application_reject, name='application_reject'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name = "password_reset.html"), name = 'reset_password'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = "password_reset_sent.html"), name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = "password_reset_form.html"), name = 'password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"), name = 'password_reset_complete'),
    
] + static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)