# Generated by Django 4.0.1 on 2022-02-06 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, default=models.EmailField(max_length=60, unique=True, verbose_name='email'), max_length=30, null=True, verbose_name='username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('mobile_number', models.CharField(max_length=255, unique=True, verbose_name='mobile number')),
                ('id_number', models.CharField(max_length=255, unique=True, verbose_name='id number')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='profession')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('gender', models.CharField(blank=True, max_length=255, null=True, verbose_name='gender')),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='marital status')),
                ('church_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='church status')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('membership_number', models.CharField(max_length=255, unique=True, verbose_name='Membership number')),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email')),
                ('membership_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mebership Number')),
                ('date_of_attendance', models.DateField(blank=True, null=True, verbose_name='Date of Attendance')),
                ('temperature', models.IntegerField(blank=True, null=True, verbose_name='Temperature')),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('date_of_baptism', models.DateField(blank=True, null=True, verbose_name='Date of Baptism')),
                ('christian_name', models.CharField(max_length=255, verbose_name='Christian Name')),
                ('father_name', models.CharField(max_length=255, verbose_name='Father Name')),
                ('mother_name', models.CharField(max_length=255, verbose_name='Mother Name')),
                ('guardian_name', models.CharField(max_length=255, verbose_name='Guardian Name')),
                ('parent_postal_address', models.CharField(max_length=255, verbose_name='Address')),
                ('mobile_number_father', models.CharField(blank=True, max_length=255, null=True, verbose_name='Father Mobile Number')),
                ('mobile_number_mother', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mother Mobile Number')),
                ('residential_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Residential Address')),
                ('date_of_marriage', models.DateField(blank=True, null=True, verbose_name='Date of Marriage')),
                ('place_of_marriage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place of Marriage')),
                ('parents_baptised', models.CharField(blank=True, max_length=255, null=True, verbose_name='Parents Baptised?')),
                ('parents_members', models.CharField(blank=True, max_length=255, null=True, verbose_name='Parents Members?')),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('theme', models.CharField(blank=True, max_length=255, null=True, verbose_name='theme')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
        migrations.CreateModel(
            name='Communion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Number')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='DoB')),
                ('date_of_communion', models.DateField(blank=True, null=True, verbose_name='Date of Communion')),
                ('postal_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('residential_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Residential Address')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('theme', models.CharField(blank=True, max_length=255, null=True, verbose_name='theme')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Event Name')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('theme', models.CharField(blank=True, max_length=255, null=True, verbose_name='theme')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('information', models.CharField(blank=True, max_length=255, null=True, verbose_name='Information')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_name', models.CharField(max_length=255, verbose_name='Husband name')),
                ('mobile_number_husband', models.CharField(blank=True, max_length=255, null=True, verbose_name='Husband Mobile Number')),
                ('husband_dob', models.DateField(blank=True, null=True, verbose_name='Husband DoB')),
                ('husband_date_of_baptism', models.DateField(blank=True, null=True, verbose_name='H. Date of Baptism')),
                ('wife_name', models.CharField(max_length=255, verbose_name='Wife name')),
                ('wife_dob', models.DateField(blank=True, null=True, verbose_name='Wife DoB')),
                ('wife_date_of_baptism', models.DateField(blank=True, null=True, verbose_name='W. Date of Baptism')),
                ('mobile_number_wife', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wife Mobile Number')),
                ('H_father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Husband Father Name')),
                ('H_mother_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Husband Mother Name')),
                ('W_father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wife Father Name')),
                ('W_mother_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wife Mother Name')),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guardian Name')),
                ('postal_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('residential_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Residential Address')),
                ('date_of_marriage', models.DateField(blank=True, null=True, verbose_name='Date of Marriage')),
            ],
        ),
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('date_applied', models.DateTimeField(auto_now_add=True, verbose_name='date applied')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('application', models.CharField(blank=True, max_length=255, null=True, verbose_name='application')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('dep_em', models.EmailField(max_length=60, unique=True, verbose_name='Dependent Email')),
                ('gender', models.CharField(blank=True, max_length=255, null=True, verbose_name='gender')),
                ('id_number', models.CharField(max_length=255, unique=True, verbose_name='ID Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('relationship', models.CharField(blank=True, max_length=255, null=True, verbose_name='relationship')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='profession')),
                ('church_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='church status')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('mobile_number', models.CharField(default='+2457', max_length=255, unique=True, verbose_name='Mobile Number')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='membership number')),
                ('parent1', models.CharField(default='1', max_length=255, verbose_name='First Parent')),
                ('membership_number', models.CharField(max_length=255, unique=True, verbose_name='Membership Number')),
                ('cluster', models.ManyToManyField(blank=True, to='ackweb.Cluster')),
                ('department', models.ManyToManyField(blank=True, to='ackweb.Department')),
                ('ministry', models.ManyToManyField(blank=True, to='ackweb.Ministry')),
                ('parent2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Second Parent')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date', models.DateField(max_length=255, verbose_name='date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ackweb.department')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='cluster',
            field=models.ManyToManyField(blank=True, to='ackweb.Cluster'),
        ),
        migrations.AddField(
            model_name='account',
            name='department',
            field=models.ManyToManyField(blank=True, to='ackweb.Department'),
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='ministry',
            field=models.ManyToManyField(blank=True, to='ackweb.Ministry'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
