# Generated by Django 4.0.1 on 2022-02-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ackweb', '0002_alter_account_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_number',
            field=models.CharField(max_length=255, verbose_name='id number'),
        ),
    ]
